import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync, mkdirSync, readdirSync } from "node:fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outdir = "e2e-vault/.obsidian/plugins/Osmosis";
const outfile = `${outdir}/main.js`;

// Ensure output directory exists
mkdirSync(outdir, { recursive: true });

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile,
	minify: prod,
});

if (prod) {
	await context.rebuild();
	// Copy manifest.json and styles.css to output directory
	copyFileSync("manifest.json", `${outdir}/manifest.json`);
	try {
		copyFileSync("styles.css", `${outdir}/styles.css`);
	} catch {
		// styles.css is optional
	}

	// Copy build output to demo vaults
	const demoDir = "demo";
	try {
		const vaults = readdirSync(demoDir, { withFileTypes: true })
			.filter(d => d.isDirectory())
			.map(d => d.name);
		for (const vault of vaults) {
			const pluginDir = `${demoDir}/${vault}/.obsidian/plugins/Osmosis`;
			mkdirSync(pluginDir, { recursive: true });
			copyFileSync(outfile, `${pluginDir}/main.js`);
			copyFileSync("manifest.json", `${pluginDir}/manifest.json`);
			try {
				copyFileSync("styles.css", `${pluginDir}/styles.css`);
			} catch {
				// styles.css is optional
			}
		}
	} catch {
		// demo directory may not exist
	}

	process.exit(0);
} else {
	await context.watch();
}
