import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outdir = "e2e-vault/.obsidian/plugins/Osmosis";
const outfile = `${outdir}/main.js`;

// Ensure output directory exists
mkdirSync(outdir, { recursive: true });

/**
 * Post-build plugin that injects the sql.js WASM binary (base64-encoded)
 * into the bundled output, replacing the placeholder string.
 */
const injectWasmPlugin = {
	name: "inject-sql-wasm",
	setup(build) {
		build.onEnd(() => {
			try {
				const wasmBuffer = readFileSync("node_modules/sql.js/dist/sql-wasm.wasm");
				const wasmBase64 = wasmBuffer.toString("base64");
				let mainJs = readFileSync(outfile, "utf8");
				mainJs = mainJs.replace(
					/"__OSMOSIS_SQL_WASM_PLACEHOLDER__"/g,
					JSON.stringify(wasmBase64),
				);
				writeFileSync(outfile, mainJs);
			} catch (err) {
				console.error("⚠ Failed to inject sql.js WASM:", err.message);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile,
	minify: prod,
	plugins: [injectWasmPlugin],
});

if (prod) {
	await context.rebuild();
	// Copy manifest.json and styles.css to output directory
	copyFileSync("manifest.json", `${outdir}/manifest.json`);
	try {
		copyFileSync("styles.css", `${outdir}/styles.css`);
	} catch {
		// styles.css is optional
	}
	process.exit(0);
} else {
	await context.watch();
}
