/**
 * Obsidian block ID utilities for "Notes as Flashcards".
 *
 * Line cards are identified by native Obsidian block IDs appended to lines
 * (e.g. `- Mitochondria produce ATP ^os-a1b2c3`). Osmosis-generated IDs use
 * the `os-` prefix, but any valid block ID already present on a line is
 * reused as the card ID.
 */

/**
 * Matches a trailing block ID at the end of a line: whitespace, a caret,
 * then one or more valid block ID characters (letters, digits, dashes).
 * Requires non-whitespace content before it — a line consisting only of
 * a block ID is not treated as carrying one.
 */
const TRAILING_BLOCK_ID_REGEX = /^(.*\S)\s+\^([a-zA-Z0-9-]+)\s*$/;

/** Prefix marking a block ID as Osmosis-generated. */
export const OSMOSIS_BLOCK_ID_PREFIX = "os-";

/** A block ID found at the end of a line. */
export interface ExtractedBlockId {
	/** The block ID without the leading caret (e.g. "os-a1b2c3"). */
	id: string;
	/** Offset within the line where the ID's preceding whitespace begins. */
	idStart: number;
	/** The line text with the trailing block ID removed. */
	stripped: string;
}

/**
 * Extract a trailing block ID from a line of markdown, if present.
 * Returns null when the line has no trailing block ID.
 */
export function extractTrailingBlockId(lineText: string): ExtractedBlockId | null {
	const match = TRAILING_BLOCK_ID_REGEX.exec(lineText);
	if (!match) return null;
	const stripped = match[1]!;
	return {
		id: match[2]!,
		idStart: stripped.length,
		stripped,
	};
}

/** Remove a trailing block ID from a line, or return the line unchanged. */
export function stripTrailingBlockId(lineText: string): string {
	return extractTrailingBlockId(lineText)?.stripped ?? lineText;
}

/** Whether a block ID was generated by Osmosis (`os-` prefix). */
export function isOsmosisBlockId(id: string): boolean {
	return id.startsWith(OSMOSIS_BLOCK_ID_PREFIX);
}

/** Base36 alphabet for generated IDs (valid block ID characters). */
const ID_ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyz";

/** Length of the random portion of a generated block ID. */
const ID_LENGTH = 6;

/**
 * Generate a new Osmosis block ID: `os-` + 6 random base36 characters
 * (e.g. "os-a1b2c3"). ~2.2 billion combinations — collisions within a
 * single note are checked by callers via `existingIds`.
 */
export function generateBlockId(existingIds?: ReadonlySet<string>): string {
	for (;;) {
		const bytes = new Uint8Array(ID_LENGTH);
		crypto.getRandomValues(bytes);
		let suffix = "";
		for (const byte of bytes) {
			suffix += ID_ALPHABET[byte % ID_ALPHABET.length];
		}
		const id = OSMOSIS_BLOCK_ID_PREFIX + suffix;
		if (!existingIds?.has(id)) return id;
	}
}
